Slobodeniuk_TasksLesson2(1-4)
=> Slobodeniuk_TasksLesson2(1-4)

Slobodeniuk_HW2
=> Slobodeniuk_HW2

SlobodeniukHW2(Additional Task Cat)
SlobodeniukHW2(Additional Task Cat)
=> SlobodeniukHW2(Additional Task Cat)

Ren_Shev-HW/Homework2/Program.cs
1. Added 5 tasks to homework 2.
2. Change condition for hw 1.
=> added tasks for hw2

Kolesov HW3/Program.cs
=> Kolesov - HW3

Ren_Shev-HW/Homework3/Program.cs
=> hw 3 is complited

Slobodeniuk_HW3
=> Slobodeniuk_HW3

SuberliakHomeworks/SuberliakHomeworks.sln, SuberliakHomeworks/SuberliakHw1.2/Program.cs, SuberliakHomeworks/SuberliakHw1.2/SuberliakHw1_2.csproj, SuberliakHomeworks/SuberliakHw1/Program.cs, SuberliakHomeworks/SuberliakHw1/SuberliakHw1_1.csproj, SuberliakHomeworks/SuberliakHw1_3/Program.cs, SuberliakHomeworks/SuberliakHw1_3/SuberliakHw1_3.csproj
HW#1:
SuberliakHomeworks/SuberliakHw1/Program.cs
HW#2:
SuberliakHomeworks/SuberliakHw1.2/Program.cs
HW#3:
SuberliakHomeworks/SuberliakHw1_3/Program.cs
=> Suberliak: Created HW for lesson 1 (Task1,2,3)

IDovhyiHomework3
Таски з уроку незакомітені, але залиті в репозиторій
=> IDovhyiHomework3

Ren_Shev-HW/Homework4/HW4-shevchuk.sln, Ren_Shev-HW/Homework4/HW4-shevchuk/App.config, Ren_Shev-HW/Homework4/HW4-shevchuk/HW4-shevchuk.csproj, Ren_Shev-HW/Homework4/HW4-shevchuk/Person.cs, Ren_Shev-HW/Homework4/HW4-shevchuk/Program.cs, Ren_Shev-HW/Homework4/HW4-shevchuk/Properties/AssemblyInfo.cs
=> hw 4 is complited

Ren_Shev-HW/Homework4/HW4-shevchuk/Program.cs
Добавлено другий варіант виводу всіх персон з однаковими іменами з використанням фільтру
=> add 2 variant for output the same names

SlobodeniukHW5_1/Builder .cs, SlobodeniukHW5_1/IDeveloper.cs, SlobodeniukHW5_1/Program.cs, SlobodeniukHW5_1/Programmers.cs, SlobodeniukHW5_2/Persons.cs, SlobodeniukHW5_2/Program.cs
=> added homework 5

Ren_Shev-HW/Homework5/Homework5.sln, Ren_Shev-HW/Homework5/Homework5/App.config, Ren_Shev-HW/Homework5/Homework5/Builder.cs, Ren_Shev-HW/Homework5/Homework5/Homework5.csproj, Ren_Shev-HW/Homework5/Homework5/IDeveloper.cs, Ren_Shev-HW/Homework5/Homework5/Program.cs, Ren_Shev-HW/Homework5/Homework5/Programmer.cs, Ren_Shev-HW/Homework5/Homework5/Properties/AssemblyInfo.cs
=> hw5 is complited

SlobodeniukHW_6
=> homework SlobodeniukHW_6

Ren_Shev-HW/Homework6/Shevchuk-HW6.sln, Ren_Shev-HW/Homework6/Shevchuk-HW6/App.config, Ren_Shev-HW/Homework6/Shevchuk-HW6/Program.cs, Ren_Shev-HW/Homework6/Shevchuk-HW6/Properties/AssemblyInfo.cs, Ren_Shev-HW/Homework6/Shevchuk-HW6/Shevchuk-HW6.csproj
=> hw 6 is complited

SuberliakHomeworks/ConsoleApp1/Program.cs, SuberliakHomeworks/ConsoleApp1/SuberliakHw2.4.csproj, SuberliakHomeworks/SuberliakHomeworks.sln, SuberliakHomeworks/SuberliakHw1_3/Program.cs, SuberliakHomeworks/SuberliakHw2.1/Program.cs, SuberliakHomeworks/SuberliakHw2.1/SuberliakHw2.1.csproj, SuberliakHomeworks/SuberliakHw2.2/Program.cs, SuberliakHomeworks/SuberliakHw2.2/SuberliakHw2.2.csproj, SuberliakHomeworks/SuberliakHw2.3/HTTPErrorsEnum.cs, SuberliakHomeworks/SuberliakHw2.3/Program.cs, SuberliakHomeworks/SuberliakHw2.3/SuberliakHw2.3.csproj
Added Homework 2 in next projects
SuberliakHw2.1
SuberliakHw2.2
SuberliakHw2.3
SuberliakHw2.4
=> Suberliak hw2

SlobodeniukHW9A/Circle.cs, SlobodeniukHW9A/Program.cs, SlobodeniukHW9A/Shape.cs, SlobodeniukHW9A/Square.cs, SlobodeniukHW9B/Program.cs
Added homework Slobodeniuk_HW9
=> Slobodeniuk_HW9

hwchornobai/hm6.cs
=> chornobai - hmw6

SlobodeniukHW10/SlobodeniukHW10Shapes/Circle.cs, SlobodeniukHW10/SlobodeniukHW10Shapes/Program.cs, SlobodeniukHW10/SlobodeniukHW10Shapes/Shape.cs, SlobodeniukHW10/SlobodeniukHW10Shapes/Square.cs, SlobodeniukHW10/SlobodeniukHW10Shapes/TestShapes.cs, SlobodeniukHW10/SlobodeniukHW10Triangle/Point.cs, SlobodeniukHW10/SlobodeniukHW10Triangle/Program.cs, SlobodeniukHW10/SlobodeniukHW10Triangle/Triangle.cs, SlobodeniukHW10/SlobodeniukHW10Triangle/TriangleTest.cs
=> SlobodeniukHW10

VSuberliakHw_3/VSuberliakHw_3.1/Program.cs, VSuberliakHw_3/VSuberliakHw_3.1/VSuberliakHw_3.1.csproj, VSuberliakHw_3/VSuberliakHw_3.2/Program.cs, VSuberliakHw_3/VSuberliakHw_3.2/VSuberliakHw_3.2.csproj, VSuberliakHw_3/VSuberliakHw_3.3/Program.cs, VSuberliakHw_3/VSuberliakHw_3.3/VSuberliakHw_3.3.csproj, VSuberliakHw_3/VSuberliakHw_3.sln
added HW 3 with task1+task2+task3
=> VSuberliak hw 3 
